routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group([
    'middleware' => 'auth',
    'prefix'     => 'admin',
    'as'         => 'admin.',
    'namespace'  => 'Admin',
], function() {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    // staff roles
    Route::resource('staff/roles', 'RoleController');
    // staff privileges
    Route::resource('staff/privileges', 'PrivilegeController');
    // staff
    Route::resource('staff', 'StaffController');
    Route::post('staff/{staff}/suspend', 'StaffController@suspend')->name('staff.suspend');
    Route::post('staff/{staff}/unsuspend', 'StaffController@unsuspend')->name('staff.unsuspend');
    // staff nok
    Route::get('staff/{staff}/noks', 'StaffNokController@index')->name('staff.noks');
    Route::get('staff/{staff}/noks/create', 'StaffNokController@create')->name('staff.noks.create');
    Route::post('staff/{staff}/noks/store', 'StaffNokController@store')->name('staff.noks.store');
    Route::get('staff/{staff}/noks/{nok}' , 'StaffNokController@show')->name('staff.noks.show');
    Route::get('staff/{staff}/noks/{nok}/edit', 'StaffNokController@edit')->name('staff.noks.edit');
    Route::put('staff/{staff}/noks/{nok}/update', 'StaffNokController@update')->name('staff.noks.update');
    Route::delete('staff/{staff}/noks/{nok}/destroy', 'StaffNokController@destroy')->name('staff.noks.destroy');
    // branches
    Route::post('staff/{staff}/branches', 'StaffController@updateBranches')->name('staff.branches.update');
    // staff role and privileges..
    Route::get('staff/{staff}/roles','StaffRoleController@index')->name('staff.roles');
    Route::put('staff/{staff}/roles', 'StaffRoleController@update')->name('staff.roles.update');
    Route::get('staff/{staff}/roles/edit', 'StaffRoleController@edit')->name('staff.roles.edit');
    Route::put('staff/{staff}/privileges', 'StaffRoleController@updatePrivileges')->name('staff.privileges.update');

    // customers
    Route::resource('customers', 'CustomerController');
    Route::get('customers/{customer}/vehicles', 'CustomerVehicleController@index')->name('customers.vehicles');

    // branch
    Route::resource('settings/branches', 'BranchController');
    Route::get('settings/branches/{branch}/staff', 'BranchController@staff')->name('branches.staff');
    Route::get('settings/branches/{branch}/customers', 'BranchController@customers')->name('branches.customers');
    // services
    Route::resource('settings/services', 'ServiceController');

    // product type
    Route::resource('products/product-type', 'ProductTypeController');

    // product
    Route::resource('products', 'ProductController');

    // vehicle fuels
    Route::resource('vehicles/vehicle-fuels', 'VehicleFuelController');
    // vehicle make
    Route::resource('vehicles/vehicle-makes', 'VehicleMakeController');
    // vehicles
    Route::resource('vehicles', 'VehicleController');
    // supplies
    Route::resource('supplies', 'SupplyController');

    Route::post('supplies/{supply}/confirm', 'SupplyController@confirmSupply')->name('supplies.confirm');
    Route::post('supplies/{supply}/items', 'SupplyItemController@store')->name('supplies.add.item');
    Route::get('supplies/{supply}/items/{id}', 'SupplyItemController@show')->name('supplies.show.item');
    Route::put('supplier/{supply}/items/{id}', 'SupplyItemController@update')->name('supplies.update.item');
    Route::delete('supplier/{supply}/items/{id}', 'SupplyItemController@destroy')->name('supplies.destroy.item');
    // suppliers
    Route::resource('suppliers', 'SupplierController');
    // job order
    Route::resource('job-orders', 'JobOrderController');
    Route::post('job-orders/{order}/manager', 'JobOrderController@assignManager')->name('job-orders.manager');

    Route::get('job-orders/{order}/inspection', 'JobOrderInspectionController@index')->name('job-orders.inspection');
    Route::put('job-orders/{order}/inspection', 'JobOrderInspectionController@update')->name('job-orders.inspection.update');
    Route::post('job-orders/{order}/inspection/results', 'JobOrderInspectionController@addItem')->name('job-orders.inspection.add-item');
    Route::put('job-orders/{order}/inspection/results/{result}', 'JobOrderInspectionController@updateItem')->name('job-orders.inspection.update-item');
    Route::delete('job-orders/{order}/inspection/results/{result}', 'JobOrderInspectionController@removeItem')->name('job-orders.inspection.remove-item');

    Route::get('job-orders/{order}/faults', 'JobOrderFaultController@index')->name('job-orders.faults');
    Route::post('job-orders/{order}/faults', 'JobOrderFaultController@store')->name('job-orders.faults.store');
    Route::get('job-orders/{order}/faults/create', 'JobOrderFaultController@create')->name('job-orders.faults.create');
    Route::put('job-orders/{order}/faults/{id}', 'JobOrderFaultController@update')->name('job-orders.faults.update');
    Route::delete('job-orders/{order}/faults/{id}', 'JobOrderFaultController@destroy')->name('job-orders.faults.destroy');

    Route::get('job-orders/{order}/services', 'JobOrderServiceController@index')->name('job-orders.services');
    Route::post('job-orders/{order}/services', 'JobOrderServiceController@store')->name('job-orders.services.store');
    Route::get('job-orders/{order}/services/{service}', 'JobOrderServiceController@show')->name('job-orders.services.show');
    Route::put('job-orders/{order}/services/{service}', 'JobOrderServiceController@update')->name('job-orders.services.update');
    Route::delete('job-orders/{order}/services/{service}', 'JobOrderServiceController@destroy')->name('job-orders.services.destroy');
    Route::get('job-orders/{order}/services/{service}/edit', 'JobOrderServiceController@edit')->name('job-orders.services.edit');

});

app/Models/Vehicle.php
<?php

namespace App\Models;

use App\Traits\Auditable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Vehicle extends Model
{
    use HasFactory, Auditable;

    protected $guarded = [];

    public function customer()
    {
        return $this->belongsTo(Customer::class);
    }

    public function make()
    {
        return $this->belongsTo(VehicleMake::class, 'vehicle_make_id');
    }

    public function fuel()
    {
        return $this->belongsTo(VehicleFuel::class);
    }

    public function createdBy()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function branch()
    {
        return $this->belongsTo(Branch::class);
    }

    public function jobOrders()
    {
        return $this->hasMany(JobOrder::class);
    }

    public function canDelete()
    {
        if ($this->jobOrders()->isEmpty()) return true;
        return false;
    }
}

app/Http/Controllers/Admin/VehicleController.php
<?php

namespace App\Http\Controllers\Admin;

use Exception;
use App\Helpers\Util;
use App\Models\Vehicle;
use App\Models\Customer;
use App\Models\VehicleFuel;
use App\Models\VehicleMake;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use App\Http\Controllers\Controller;
use App\Repositories\VehicleRepository;
use App\Repositories\CustomerRepository;

class VehicleController extends Controller
{
    public $vehicleRepo;
    public $customerRepo;

    public function __construct(VehicleRepository $vehicleRepo, CustomerRepository $customerRepo)
    {
        $this->vehicleRepo = $vehicleRepo;
        $this->customerRepo = $customerRepo;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $vehicles = Vehicle::orderByDesc('id')->get();

        return view('admin.vehicles.index')
            ->with('vehicles', $vehicles);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param \Illuminate\Http\Request $request
     * 
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $customers = Customer::all();

        if (!$customers->count()) {
            return redirect()->route('admin.customers.create')
                ->with('warning', 'Create a customer to add a vehicle record');
        }
        
       
        $vehicle_makes = VehicleMake::all();
        $vheicle_fuels = VehicleFuel::all();

        return view('admin.vehicles.create')
            ->with('vehicle_fuels', $vheicle_fuels)
            ->with('vehicle_makes', $vehicle_makes)
            ->with('customers', $customers)
            ->with('customer_id', $request->customer ?? null);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // remove unwanted keys
        $request->request->remove('branch');
        // find customer
        $customer = $this->customerRepo->findById($request->customer_id);

        if ($vehicle = $this->vehicleRepo->store($request, $customer)) {
            $msg = [
                'title'   => 'Vehicle Record Created',
                'message' => 'vehicle with number '.$vehicle->plate_number.' was successfully created'
            ];

            return redirect()->route('admin.vehicles.show', $vehicle->id)
                ->with('success', $msg);
        }

        return redirect()->back()->withInput()->with('error', 'Vehicle was not created! Try again');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $vehicle = Vehicle::with(['customer', 'make', 'fuel'])->findOrFail($id);

        return view('admin.vehicles.show')
            ->with('vehicle', $vehicle);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $vehicle = Vehicle::findOrFail($id);

        $vehicle_makes = VehicleMake::all();
        $vehicle_fuels = VehicleFuel::all();
        $customers = Customer::all();

        return view('admin.vehicles.edit')
            ->with('vehicle', $vehicle)
            ->with('vehicle_makes', $vehicle_makes)
            ->with('vehicle_fuels', $vehicle_fuels)
            ->with('customers', $customers);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $vehicle = Vehicle::findOrFail($id);
        try {
            $this->vehicleRepo->update($request, $vehicle);

            $msg = [
                'title' => 'Vehicle Updated',
                'message' => 'Vehicle was successfully updated',
            ];

            return redirect()->route('admin.vehicles.show', $vehicle->id)
                ->with('success', $msg);

        } catch (Exception $ex) {
            Log::error($ex->getMessage());

            return redirect()->back()->withInput()
                ->with('error', 'Oops! something went wrong! Try again!');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $vehicle = Vehicle::findOrFail($id);

        if ($vehicle->canDelete()) {
            $vehicle->delete();

            $msg = [
                'title'   => 'Vehicle Deleted',
                'message' => 'vehicle with plate number, '.$vehicle->plate_number.' was successfully deleted',
            ];

            Util::flash('success', $msg);

            return response()->json([
                'success' => true,
                'message' => $msg['message'],
                'redirect' => route('admin.vehicles.index'),
            ]);
        }

        return response()->json([
            'success' => false,
            'message' => 'deletion of vehicle failed! Try again!',
        ], 400);
    }
}

resources/views/admin/vehicles/create.blade.php
@extends('layouts.admin.app')

@section('title', 'New Vehicle')
@section('page_title', 'New Vehicle')

@push('breadcrumb')
    <li class="breadcrumb-item">
        <a href="{{ route('admin.vehicles.create') }}">Vehicles</a>
    </li>
    <li class="breadcrumb-item active">
        New
    </li>
@endpush

@push('css')
    
@endpush

@section('content')
    <div class="row">
        <div class="col-12">
           <div class="card">
               <form action="{{ route('admin.vehicles.store') }}" method="POST">
                    @csrf
                    <div class="card-body">
                        <h4 class="header-title">New Vehicle Record</h4>
                        <p class="font-13 sub-header"></p>
                        <div class="row">
                            <div class="offset-md-3 col-md-6">
                                @if ($errors->any())
                                    <div class="alert alert-danger alert-dismissable">
                                        {{ $errors->first() }}
                                        <button class="close" type="button" data-dismiss="modal">
                                            <span>&times;</span>
                                        </button>
                                    </div>
                                @endif
                                <div class="form-group">
                                    <label for="customer">Customer</label>
                                    <x-form.select
                                        name="customer_id"
                                        id="customer"
                                        required
                                    >
                                        <option value="">Choose Customer</option>
                                        @foreach ($customers as $customer)
                                            <option value="{{ $customer->id }}"
                                                @if ($customer_id == $customer->id)
                                                    selected
                                                @elseif (old('customer_id') == $customer->id)
                                                    selected
                                                @endif    
                                            >
                                                {{ $customer->name }} ({{ $customer->branch->name }})
                                            </option>
                                        @endforeach
                                    </x-form.select>
                                </div>

                                {{-- branch --}}
                                <div class="form-group">
                                    <label for="branch">Branch</label>
                                    <x-form.input
                                        name="branch"
                                        id="branch"
                                        readonly
                                        value="{{ $admin->branch->name }}"
                                    ></x-form.input>
                                </div>

                                {{-- vehicle make --}}
                                <div class="form-group">
                                    <label for="vehicle_make">Vehicle Make</label>
                                    <x-form.select
                                        name="vehicle_make_id"
                                        id="vehicle_make"
                                        required
                                    >
                                        <option value="">Choose Vehicle Make</option>
                                        @foreach ($vehicle_makes as $make)
                                            <option value="{{ $make->id }}"
                                                 @if (old('vehicle_make_id') == $make->id)selected @endif     
                                            >
                                                {{ $make->name }}
                                            </option>
                                        @endforeach
                                    </x-form.select>
                                </div>

                                {{-- vehicle fuel --}}
                                <div class="form-group">
                                    <label for="vehicle_fuel">Vehicle Fuel</label>
                                    <x-form.select
                                        name="vehicle_fuel_id"
                                        id="vehicle_fuel"
                                        required
                                    >
                                        <option value="">Choose vehicle fuel</option>
                                        @foreach ($vehicle_fuels as $fuel)
                                            <option value="{{ $fuel->id }}"
                                                @if (old('vehicle_fuel_id') == $fuel->id)selected @endif    
                                            >
                                                {{ $fuel->name }}
                                            </option>
                                        @endforeach
                                    </x-form.select>
                                </div>

                                {{-- plat number --}}
                                <div class="form-group">
                                    <label for="plate_number">Plate Number</label>
                                    <x-form.input
                                        name="plate_number"
                                        id="plate_number"
                                        required
                                        value="{{ old('plate_number') }}"
                                    ></x-form.input>
                                </div>

                                {{-- model --}}
                                <div class="form-group">
                                    <label for="model">Model</label>
                                    <x-form.input
                                        name="model"
                                        id="model"
                                        value="{{ old('model') }}"
                                    ></x-form.input>
                                </div>

                                {{-- model year --}}
                                <div class="form-group">
                                    <label for="model_year">Model Year</label>
                                    <x-form.input
                                        name="model_year"
                                        id="model_year"
                                        value="{{ old('model_year') }}"
                                    ></x-form.input>
                                </div>

                                {{-- engine number  --}}
                                <div class="form-group">
                                    <label for="enginer_number">Engine Number</label>
                                    <x-form.input
                                        name="engine_number"
                                        id="engine_number"
                                        value="{{ old('engine_number') }}"
                                    ></x-form.input>
                                </div>

                                {{-- gear box number --}}
                                <div class="form-group">
                                    <label for="gearbox_number">Gear Box Number</label>
                                    <x-form.input
                                        name="gearbox_number"
                                        id="gearbox_number"
                                        value="{{ old('gearbox_number') }}"
                                    ></x-form.input>
                                </div>

                                {{-- color --}}
                                <div class="form-group">
                                    <label for="color">Color</label>
                                    <x-form.input
                                        name="color"
                                        id="color"
                                        required
                                        type="color"
                                        value="{{ old('color') }}"
                                    ></x-form.input>
                                </div>

                                {{-- description --}}
                                <div class="form-group">
                                    <label for="description">Description</label>
                                    <x-form.textarea
                                        name="description"
                                        id="description"
                                    >{{ old('description') }}</x-form.textarea>
                                </div>

                                <div class="form-group mt-5 mb-4 text-center">
                                    <button class="btn btn-secondary btn-lg waves-effect px-5" type="submit">
                                        Save Record
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
               </form>
           </div>
        </div>
    </div>
@endsection

@push('js')
    
@endpush

resources/views/admin/vehicles/show.blade.php
@extends('layouts.admin.app')

@section('title', 'Vehicle - '.$vehicle->reference)
@section('page_title', 'Vehicle - '.$vehicle->reference)

@push('breadcrumb')
    {{-- <li class="breadcrumb-item">
        <a href="{{ route('admin.customers.index') }}">Customers</a>
    </li> --}}
    <li class="breadcrumb-item">
        <a href="{{ route('admin.customers.show', $vehicle->customer->id) }}">
            {{ Str::limit($vehicle->customer->name, 15) }}
        </a>
    </li>
    <li class="breadcrumb-item">
        <a href="{{ route('admin.customers.vehicles', $vehicle->customer_id) }}">Vehicles</a>
    </li>
    <li class="breadcrumb-item active">
        {{ $vehicle->reference }}
    </li>
@endpush

@push('css')
    
@endpush

@section('content')
    <div class="row">
        <div class="col-md-9 order-2 order-md-1">
            <div class="card mb-4">
                <div class="card-body">
                    <h4 class="header-title">Vehicle Details</h4>
                    <p class="font-13 subheader-title"></p>
                    <div>
                        <table class="table table-borderless">
                            <thead>
                                <th width="25%"></th>
                                <th></th>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>Reference</td>
                                    <td>{{ $vehicle->reference }}</td>
                                </tr>
                                <tr>
                                    <td>Plate Number</td>
                                    <td>{{ $vehicle->plate_number }}</td>
                                </tr>
                                <tr>
                                    <td>Customer</td>
                                    <td>
                                        @can('view', $vehicle->customer)
                                            <a href="{{ route('admin.customers.show', $vehicle->customer_id) }}">
                                                {{ $vehicle->customer->name }}
                                            </a>
                                        @else
                                            {{ $vehicle->customer->name }}
                                        @endcan
                                    </td>
                                </tr>
                                <tr>
                                    <td>Phone Number</td>
                                    <td>{{ $vehicle->customer->phone ?? '-' }}</td>
                                </tr>
                                <tr>
                                    <td>Branch</td>
                                    <td>{{ $vehicle->branch->name }}</td>
                                </tr>
                                <tr>
                                    <td>Fuel</td>
                                    <td>{{ $vehicle->fuel }}</td>
                                </tr>
                                <tr>
                                    <td>Make</td>
                                    <td>{{ $vehicle->make->name }}</td>
                                </tr>
                                <tr>
                                    <td>Plate Number</td>
                                    <td>{{ $vehicle->plate_number }}</td>
                                </tr>
                                <tr>
                                    <td>Engine Number</td>
                                    <td>{{ $vehicle->engine_number ?? '-' }}</td>
                                </tr>
                                <tr>
                                    <td>Gearbox Number</td>
                                    <td>{{ $vehicle->gearbox_number ?? '-' }}</td>
                                </tr>
                                <tr>
                                    <td>Color</td>
                                    <td>
                                        <span class="chip chip-sm" 
                                            style="background-color: {{ $vehicle->color }}; padding: 4px; width:65%;"
                                        >
                                            {{ $vehicle->color }}
                                        </span>
                                    </td>
                                </tr>
                                <tr>
                                    <td>Added On</td>
                                    <td>{{ $vehicle->created_at->format('jS M, Y @ h:i a') }}</td>
                                </tr>
                                <tr>
                                    <td>Last Updated On</td>
                                    <td>{{ $vehicle->updated_at->format('jS M, Y @ h:i a') }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="card mb-4">
                <div class="card-body">
                    <h4 class="header-title mb-4">Job Orders</h4>
                    @if ($vehicle->jobOrders->isNotEmpty())
                        <div class="">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>

                                </tbody>
                            </table>
                        </div>
                    @else
                        <div class="text-center my-3">
                            <h4 class="text-muted">
                                No job order found!
                            </h4>
                        </div>
                    @endif
                </div>
            </div>
        </div>
        <div class="col-md-3 order-1 order-md-2">
            <a href="{{ route('admin.vehicles.edit', $vehicle->id) }}" class="btn btn-warning btn-block mb-2">
                Edit
            </a>
            <button class="btn btn-danger waves-effect btn-block mb-2 delete_vehicle_btn"
                data-url="{{ route('admin.vehicles.destroy', $vehicle->id) }}"
                data-name="{{ $vehicle->plate_number }}"
            >
                Delete
            </button>
            <a href="{{ route('admin.customers.show', $vehicle->customer_id) }}" class="btn btn-block btn-secondary waves-effect mb-2">
                Customer
            </a>
            <a href="" class="btn btn-block btn-secondary waves-effect mb-2">
                New Job Order
            </a>
        </div>
    </div>
@endsection

@push('js')
    <script src="{{ asset('js/admin/vehicle.js') }}"></script>
@endpush