routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group([
    'middleware' => 'auth',
    'prefix'     => 'admin',
    'as'         => 'admin.',
    'namespace'  => 'Admin',
], function() {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    // staff roles
    Route::resource('staff/roles', 'RoleController');
    // staff privileges
    Route::resource('staff/privileges', 'PrivilegeController');
    // staff
    Route::resource('staff', 'StaffController');
    Route::post('staff/{staff}/suspend', 'StaffController@suspend')->name('staff.suspend');
    Route::post('staff/{staff}/unsuspend', 'StaffController@unsuspend')->name('staff.unsuspend');
    // staff nok
    Route::get('staff/{staff}/noks', 'StaffNokController@index')->name('staff.noks');
    Route::get('staff/{staff}/noks/create', 'StaffNokController@create')->name('staff.noks.create');
    Route::post('staff/{staff}/noks/store', 'StaffNokController@store')->name('staff.noks.store');
    Route::get('staff/{staff}/noks/{nok}' , 'StaffNokController@show')->name('staff.noks.show');
    Route::get('staff/{staff}/noks/{nok}/edit', 'StaffNokController@edit')->name('staff.noks.edit');
    Route::put('staff/{staff}/noks/{nok}/update', 'StaffNokController@update')->name('staff.noks.update');
    Route::delete('staff/{staff}/noks/{nok}/destroy', 'StaffNokController@destroy')->name('staff.noks.destroy');
    // branches
    Route::post('staff/{staff}/branches', 'StaffController@updateBranches')->name('staff.branches.update');
    // staff role and privileges..
    Route::get('staff/{staff}/roles','StaffRoleController@index')->name('staff.roles');
    Route::put('staff/{staff}/roles', 'StaffRoleController@update')->name('staff.roles.update');
    Route::get('staff/{staff}/roles/edit', 'StaffRoleController@edit')->name('staff.roles.edit');
    Route::put('staff/{staff}/privileges', 'StaffRoleController@updatePrivileges')->name('staff.privileges.update');

    // customers
    Route::resource('customers', 'CustomerController');
    Route::get('customers/{customer}/vehicles', 'CustomerVehicleController@index')->name('customers.vehicles');

    // branch
    Route::resource('settings/branches', 'BranchController');
    Route::get('settings/branches/{branch}/staff', 'BranchController@staff')->name('branches.staff');
    Route::get('settings/branches/{branch}/customers', 'BranchController@customers')->name('branches.customers');
    // services
    Route::resource('settings/services', 'ServiceController');

    // product type
    Route::resource('products/product-type', 'ProductTypeController');

    // product
    Route::resource('products', 'ProductController');

    // vehicle fuels
    Route::resource('vehicles/vehicle-fuels', 'VehicleFuelController');
    // vehicle make
    Route::resource('vehicles/vehicle-makes', 'VehicleMakeController');
    // vehicles
    Route::resource('vehicles', 'VehicleController');
    // supplies
    Route::resource('supplies', 'SupplyController');

    Route::post('supplies/{supply}/confirm', 'SupplyController@confirmSupply')->name('supplies.confirm');
    Route::post('supplies/{supply}/items', 'SupplyItemController@store')->name('supplies.add.item');
    Route::get('supplies/{supply}/items/{id}', 'SupplyItemController@show')->name('supplies.show.item');
    Route::put('supplier/{supply}/items/{id}', 'SupplyItemController@update')->name('supplies.update.item');
    Route::delete('supplier/{supply}/items/{id}', 'SupplyItemController@destroy')->name('supplies.destroy.item');
    // suppliers
    Route::resource('suppliers', 'SupplierController');
    // job order
    Route::resource('job-orders', 'JobOrderController');
    Route::post('job-orders/{order}/manager', 'JobOrderController@assignManager')->name('job-orders.manager');

    Route::get('job-orders/{order}/inspection', 'JobOrderInspectionController@index')->name('job-orders.inspection');
    Route::put('job-orders/{order}/inspection', 'JobOrderInspectionController@update')->name('job-orders.inspection.update');
    Route::post('job-orders/{order}/inspection/results', 'JobOrderInspectionController@addItem')->name('job-orders.inspection.add-item');
    Route::put('job-orders/{order}/inspection/results/{result}', 'JobOrderInspectionController@updateItem')->name('job-orders.inspection.update-item');
    Route::delete('job-orders/{order}/inspection/results/{result}', 'JobOrderInspectionController@removeItem')->name('job-orders.inspection.remove-item');

    Route::get('job-orders/{order}/faults', 'JobOrderFaultController@index')->name('job-orders.faults');
    Route::post('job-orders/{order}/faults', 'JobOrderFaultController@store')->name('job-orders.faults.store');
    Route::get('job-orders/{order}/faults/create', 'JobOrderFaultController@create')->name('job-orders.faults.create');
    Route::put('job-orders/{order}/faults/{id}', 'JobOrderFaultController@update')->name('job-orders.faults.update');
    Route::delete('job-orders/{order}/faults/{id}', 'JobOrderFaultController@destroy')->name('job-orders.faults.destroy');

    Route::get('job-orders/{order}/services', 'JobOrderServiceController@index')->name('job-orders.services');
    Route::post('job-orders/{order}/services', 'JobOrderServiceController@store')->name('job-orders.services.store');
    Route::get('job-orders/{order}/services/{service}', 'JobOrderServiceController@show')->name('job-orders.services.show');
    Route::put('job-orders/{order}/services/{service}', 'JobOrderServiceController@update')->name('job-orders.services.update');
    Route::delete('job-orders/{order}/services/{service}', 'JobOrderServiceController@destroy')->name('job-orders.services.destroy');
    Route::get('job-orders/{order}/services/{service}/edit', 'JobOrderServiceController@edit')->name('job-orders.services.edit');

});

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function users()
    {
        return $this->belongsToMany(User::class, 'user_roles');
    }

    public function privileges()
    {
        return $this->belongsToMany(Privilege::class, 'role_privileges');
    }

    public function canDelete()
    {
        if ($this->users->count()) return false;
        return true;
    }
}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use Exception;
use App\Models\Role;
use App\Models\Privilege;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use App\Http\Controllers\Controller;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::all();

        return view('admin.roles.index')
            ->with('roles', $roles);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $privileges = Privilege::all();

        return view('admin.roles.create')
            ->with('privileges', $privileges);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'        => 'required|string|max:191|unique:roles,name',
            'description' => 'nullable|string',
            'privileges' => 'required'
        ]);

        $role = Role::create($request->only('name', 'description'));
        $role->privileges()->attach($request->privileges);
        
        $msg = [
            'title'   => 'Role Created',
            'message' => 'Role '.$role->name.' was successfully created',
        ];

        return redirect()->route('admin.roles.show', $role->id)
            ->with('success', $msg);
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $role = Role::with(['privileges', 'users'])->findOrFail($id);

        return view('admin.roles.show')
            ->with('role', $role);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::with(['privileges'])->findOrFail($id);
        $privileges = Privilege::all();

        return view('admin.roles.edit')
            ->with('role', $role)
            ->with('privileges', $privileges);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'        => 'required|string|max:191|unique:roles,name,'.$request->name.',name',
            'description' => 'nullable|string',
            'privileges'  => 'required'
        ]);

        $role = Role::findOrFail($id);

        try {
            
            $role->update($request->only('name', 'description'));
            $role->privileges()->sync($request->privileges);

            $msg = [
                'title'   => 'Role Updated',
                'message' => 'Role '.$role->name.' was successfully updated',
            ];

            return redirect()->route('admin.roles.show', $id)
                ->with('success', $msg);

        } catch (Exception $ex) {  
            // on update failure   
            Log::error($ex->getMessage());

            $msg = [
                'title'   => 'Role Update Failed',
                'message' => 'Role update was not successful! Try again',
            ];

            return redirect()->back()
                ->with('error', $msg);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::findOrFail($id);

        if ($role->canDelete()) {
            $role->privileges()->detach();
            $role->delete();

            $msg = [
                'title'   => 'Role Deleted',
                'message' => 'Role '.$role->name.' was successfully deleted',
            ];

            request()->session()->flash('success', $msg);
            return response()->json([
                'success'  => true,
                'redirect' => route('admin.roles.index'),
                'message'  => $msg['message'],
            ]);
        }

        return response()->json([
            'success' => false,
            'message' => 'Role '.$role->name.' was not deleted! Try again'
        ]);

    }
}

resources/views/admin/staff/roles/edit.blade.php
@extends('layouts.admin.app')

@section('title', $user->full_name. ' - Edit Roles & Privileges')
@section('page_title', $user->full_name. ' - Edit Roles & Privileges')

@push('breadcrumb')
    <li class="breadcrumb-item">
        <a href="{{ route('admin.staff.index') }}">Staff</a>
    </li>
    <li class="breadcrumb-item ">
        <a href="{{ route('admin.staff.show', $user->id) }}">{{ Str::limit($user->full_name, 15) }}</a>
    </li>
    <li class="breadcrumb-item">
        <a href="{{ route('admin.staff.roles', $user->id) }}">Roles</a>
    </li>
    <li class="breadcrumb-item active">
        Edit
    </li>
@endpush

@push('css')
    <link rel="stylesheet" href="{{ asset('css/select2.min.css') }}">
@endpush

@section('content')
    <div class="row">
        <div class="col-12">
            {{-- role --}}
            <div class="card mb-4">
                <form action="{{ route('admin.staff.roles.update', $user->id) }}" method="POST">
                    @csrf
                    @method('put')
                    <div class="card-body">
                        <h4 class="header-title mb-3">Update Role</h4>
                        <div class="form-group">
                            <label for="roles">Roles</label>
                            <x-form.select
                                id="roles"
                                name="roles[]"
                                required
                                multiple
                            >
                                <option value="">Choose Role(s)</option>
                                @foreach ($roles as $role)
                                    <option value="{{ $role->id }}"
                                        @if (in_array($role->id, $user->roles->pluck('id')->toArray()))
                                            selected
                                        @endif    
                                    >
                                        {{ $role->name }}
                                    </option>
                                @endforeach
                            </x-form.select>
                        </div>
                        <div class="form-group text-center mt-3">
                            <button class="btn btn-secondary waves-effect" type="submit">
                                Save Role(s)
                            </button>
                        </div>
                    </div>
                </form>
            </div>

            {{-- privileges --}}
            <div class="card mb-4">
                <form action="{{ route('admin.staff.privileges.update', $user->id) }}" method="POST">
                    @csrf
                    @method('put')
                    <div class="card-body">
                        <h4 class="header-title mb-3">Update Privilege</h4>
                        <div class="form-group">
                            <label for="privileges">Privileges</label>
                            <x-form.select
                                name="privileges[]"
                                id="privileges"
                                required
                                multiple
                            >
                                <option value="">Choose Privilege(s)</option>
                                @foreach ($privileges->groupBy('category') as $key => $privilege)
                                    <optgroup label="{{ $key }}">
                                        @foreach ($privileges->where('category', $key) as $priv)
                                            <option value="{{ $priv->id }}"
                                                @if (in_array($priv->id, $user->privileges->pluck('id')->toArray()))
                                                    selected
                                                @endif    
                                            >
                                                {{ $priv->name }}
                                            </option>
                                        @endforeach
                                    </optgroup>
                                @endforeach
                            </x-form.select>
                        </div>
                        <div class="form-group mt-3 text-center">
                            <button class="btn btn-secondary waves-effect" type="submit">
                                Save Privilege(s)
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <script src="{{ asset('js/select2.min.js') }}"></script>
    <script src="{{ asset('js/admin/staff.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('#roles').select2({
                placeholder: 'Choose Role(s)',
            });

            $('#privileges').select2({
                placeholder: 'Choose Privilege(s)',
            });
        })
    </script>
@endpush

resources/views/admin/staff/roles/index.blade.php
@extends('layouts.admin.app')

@section('title', $user->full_name. ' - Roles & Privileges')
@section('page_title', $user->full_name. ' - Roles & Privileges')

@push('breadcrumb')
    <li class="breadcrumb-item">
        <a href="{{ route('admin.staff.index') }}">Staff</a>
    </li>
    <li class="breadcrumb-item ">
        <a href="{{ route('admin.staff.show', $user->id) }}">{{ Str::limit($user->full_name, 15) }}</a>
    </li>
    <li class="breadcrumb-item active">
        Roles
    </li>
@endpush

@push('css')
    
@endpush

@section('content')
    <div class="row">
        <div class="col-12">
            {{-- roles --}}
            <div class="card mb-4">
                <div class="card-body">
                    <h4 class="header-title mb-4">Roles</h4>
                    <p class="font-13 subheader-title"></p>
                    @if ($user->roles->isNotEmpty())
                        <div class="row">
                            @foreach ($user->roles as $role)
                                <div class="col-md-4">
                                    <span class="chip">{{ $role->name }}</span>
                                </div>
                            @endforeach
                            <div class="text-right col-12 mt-2">
                                <a href="{{ route('admin.staff.roles.edit', $user->id) }}">
                                    <span class="fas fa-pencil-alt"></span>
                                </a>
                            </div>
                        </div>
                    @else
                        <div class="text-center my-4">
                            <h4 class="text-muted">No role found!</h4>
                            <a href="{{ route('admin.staff.roles.edit', $user->id) }}" class="btn btn-dark mt-3 waves-effect">
                                Assign Roles
                            </a>
                        </div>
                    @endif
                </div>
            </div>
            {{-- privileges --}}
            <div class="card mb-4">
                <div class="card-body">
                    <h4 class="header-title">Privileges</h4>
                    <p class="subheader-title font-13"></p>
                    @if ($user->privileges->count())
                        <div class="row">
                            @foreach ($user->privileges as $privilege)
                                <div class="col-lg-3 col-md-4">
                                    <span class="chip">{{ $privilege->name }}</span>
                                </div>
                            @endforeach
                            <div class="col-12 text-right mt-3">
                                <a href="{{ route('admin.staff.roles.edit', $user->id) }}">
                                    <span class="fas fa-pencil-alt"></span>
                                </a>
                            </div>
                        </div>
                    @else
                        <div class="text-center my-3">
                            <h4 class="text-muted">No privilege found!</h4>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <script src="{{ asset('js/admin/staff.js') }}"></script>
@endpush