routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group([
    'middleware' => 'auth',
    'prefix'     => 'admin',
    'as'         => 'admin.',
    'namespace'  => 'Admin',
], function() {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    // staff roles
    Route::resource('staff/roles', 'RoleController');
    // staff privileges
    Route::resource('staff/privileges', 'PrivilegeController');
    // staff
    Route::resource('staff', 'StaffController');
    Route::post('staff/{staff}/suspend', 'StaffController@suspend')->name('staff.suspend');
    Route::post('staff/{staff}/unsuspend', 'StaffController@unsuspend')->name('staff.unsuspend');
    // staff nok
    Route::get('staff/{staff}/noks', 'StaffNokController@index')->name('staff.noks');
    Route::get('staff/{staff}/noks/create', 'StaffNokController@create')->name('staff.noks.create');
    Route::post('staff/{staff}/noks/store', 'StaffNokController@store')->name('staff.noks.store');
    Route::get('staff/{staff}/noks/{nok}' , 'StaffNokController@show')->name('staff.noks.show');
    Route::get('staff/{staff}/noks/{nok}/edit', 'StaffNokController@edit')->name('staff.noks.edit');
    Route::put('staff/{staff}/noks/{nok}/update', 'StaffNokController@update')->name('staff.noks.update');
    Route::delete('staff/{staff}/noks/{nok}/destroy', 'StaffNokController@destroy')->name('staff.noks.destroy');
    // branches
    Route::post('staff/{staff}/branches', 'StaffController@updateBranches')->name('staff.branches.update');
    // staff role and privileges..
    Route::get('staff/{staff}/roles','StaffRoleController@index')->name('staff.roles');
    Route::put('staff/{staff}/roles', 'StaffRoleController@update')->name('staff.roles.update');
    Route::get('staff/{staff}/roles/edit', 'StaffRoleController@edit')->name('staff.roles.edit');
    Route::put('staff/{staff}/privileges', 'StaffRoleController@updatePrivileges')->name('staff.privileges.update');

    // customers
    Route::resource('customers', 'CustomerController');
    Route::get('customers/{customer}/vehicles', 'CustomerVehicleController@index')->name('customers.vehicles');

    // branch
    Route::resource('settings/branches', 'BranchController');
    Route::get('settings/branches/{branch}/staff', 'BranchController@staff')->name('branches.staff');
    Route::get('settings/branches/{branch}/customers', 'BranchController@customers')->name('branches.customers');
    // services
    Route::resource('settings/services', 'ServiceController');

    // product type
    Route::resource('products/product-type', 'ProductTypeController');

    // product
    Route::resource('products', 'ProductController');

    // vehicle fuels
    Route::resource('vehicles/vehicle-fuels', 'VehicleFuelController');
    // vehicle make
    Route::resource('vehicles/vehicle-makes', 'VehicleMakeController');
    // vehicles
    Route::resource('vehicles', 'VehicleController');
    // supplies
    Route::resource('supplies', 'SupplyController');

    Route::post('supplies/{supply}/confirm', 'SupplyController@confirmSupply')->name('supplies.confirm');
    Route::post('supplies/{supply}/items', 'SupplyItemController@store')->name('supplies.add.item');
    Route::get('supplies/{supply}/items/{id}', 'SupplyItemController@show')->name('supplies.show.item');
    Route::put('supplier/{supply}/items/{id}', 'SupplyItemController@update')->name('supplies.update.item');
    Route::delete('supplier/{supply}/items/{id}', 'SupplyItemController@destroy')->name('supplies.destroy.item');
    // suppliers
    Route::resource('suppliers', 'SupplierController');
    // job order
    Route::resource('job-orders', 'JobOrderController');
    Route::post('job-orders/{order}/manager', 'JobOrderController@assignManager')->name('job-orders.manager');

    Route::get('job-orders/{order}/inspection', 'JobOrderInspectionController@index')->name('job-orders.inspection');
    Route::put('job-orders/{order}/inspection', 'JobOrderInspectionController@update')->name('job-orders.inspection.update');
    Route::post('job-orders/{order}/inspection/results', 'JobOrderInspectionController@addItem')->name('job-orders.inspection.add-item');
    Route::put('job-orders/{order}/inspection/results/{result}', 'JobOrderInspectionController@updateItem')->name('job-orders.inspection.update-item');
    Route::delete('job-orders/{order}/inspection/results/{result}', 'JobOrderInspectionController@removeItem')->name('job-orders.inspection.remove-item');

    Route::get('job-orders/{order}/faults', 'JobOrderFaultController@index')->name('job-orders.faults');
    Route::post('job-orders/{order}/faults', 'JobOrderFaultController@store')->name('job-orders.faults.store');
    Route::get('job-orders/{order}/faults/create', 'JobOrderFaultController@create')->name('job-orders.faults.create');
    Route::put('job-orders/{order}/faults/{id}', 'JobOrderFaultController@update')->name('job-orders.faults.update');
    Route::delete('job-orders/{order}/faults/{id}', 'JobOrderFaultController@destroy')->name('job-orders.faults.destroy');

    Route::get('job-orders/{order}/services', 'JobOrderServiceController@index')->name('job-orders.services');
    Route::post('job-orders/{order}/services', 'JobOrderServiceController@store')->name('job-orders.services.store');
    Route::get('job-orders/{order}/services/{service}', 'JobOrderServiceController@show')->name('job-orders.services.show');
    Route::put('job-orders/{order}/services/{service}', 'JobOrderServiceController@update')->name('job-orders.services.update');
    Route::delete('job-orders/{order}/services/{service}', 'JobOrderServiceController@destroy')->name('job-orders.services.destroy');
    Route::get('job-orders/{order}/services/{service}/edit', 'JobOrderServiceController@edit')->name('job-orders.services.edit');

});

app/Http/Controllers/Admin/StaffController.php
<?php

namespace App\Http\Controllers\Admin;

use Exception;
use Carbon\Carbon;
use App\Models\Role;
use App\Models\User;
use App\Helpers\Util;
use App\Models\Branch;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use App\Http\Controllers\Controller;

class StaffController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $per_page = 9;
        $search = strtolower($request->search) ?? null;

        if ($search) {
            $users = User::where('first_name', 'LIKE', $search.'%')
                ->orWhere('last_name', 'LIKE', $search,'%')
                ->orWhere('middle_name', 'LIKE', $search.'%')
                ->orWhere('email', 'LIKE', $search.'%')
                ->orWhere('phone', 'LIKE', $search.'%')
                ->paginate($per_page);
        } else {
            $users = User::orderByDesc('id')->paginate($per_page);
        }
        
        return view('admin.staff.index')
            ->with('users', $users)
            ->with('search', $search);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::has('privileges')->get();
        $genders = User::genders;
        $branches = Branch::all();

        return view('admin.staff.create')
            ->with('roles', $roles)
            ->with('genders', $genders)
            ->with('branches', $branches);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'first_name'    => 'required|string|max:191',
            'middle_name'   => 'nullable|string|max:191',
            'last_name'     => 'required|string|max:191',
            'email'         => 'required|string|max:191|email|unique:users,email',
            'phone'         => 'required|string|digits_between:7,15',
            'gender'        => 'required|string',
            'dob'           => 'nullable|date',
            'address'       => 'nullable|string',
            'roles'         => 'required',
            'image'         => 'nullable|image|mimes:jpg,png,gif,jpeg|max:500',
        ], [], [
            'dob' => 'date of birth',
        ]);

        $request->request->add(['branch_id' => $this->currentBranch()->id ]);
        
        try {
            //code...
            $user = User::create($request->all());
            
            // assign role/privileges
            $user->assignRoles($request->roles);
            $this->handleImageUpload($request, $user);

            // assign branch
            $user->branches()->attach($this->currentBranch()->id);

            $msg = [
                'title'    => 'Staff Account Created',
                'message' => 'staff account for , '.$user->full_name.'  was successfully created',
            ];

            return redirect()->route('admin.staff.show', $user->id)
                ->with('success', $msg);

        } catch (Exception $ex) {
            //log error
            Log::error($ex->getMessage());

            $msg = [
                'title'   => 'Account Creation Failed',
                'message' => 'account was not created! Try again!'
            ];

            return redirect()->back()
                ->with('error', $msg)
                ->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);
        $branches  = Branch::all();

        return view('admin.staff.show')
            ->with('user', $user)
            ->with('branches', $branches);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::with(['roles'])->findOrFail($id);
        $genders = User::genders;

        return view('admin.staff.edit')
            ->with('user', $user)
            ->with('genders', $genders);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'first_name'  => 'required|string|max:191',
            'middle_name' => 'nullable|string|max:191',
            'last_name'   => 'required|string|max:191',
            'email'       => 'required|string|max:191|email|unique:users,email,'.$request->email.',email',
            'phone'       => 'required|string|digits_between:7,15',
            'gender'      => 'required|string',
            'dob'         => 'nullable|date',
            'address'     => 'nullable|string',
            'image'       => 'nullable|image|mimes:jpg,jpeg,png,gif|max:500',
        ], [], [
            'dob' => 'date of birth',
        ]);

        $user = User::findOrFail($id);

        try {
            
        $user->update($request->all());
            $this->handleImageUpload($request, $user);

            $msg = [
                'title'   => 'Staff Account Updated',
                'message' => 'staff account was successfully updated'
            ];

            return redirect()->route('admin.staff.show', $id)
                ->with('success', $msg);

        } catch (Exception $ex) {
            //log error
            Log::error($ex->getMessage());

            $msg = [
                'title'   => 'Update Failed',
                'message' => 'staff update failed! Try again'
            ];

            return redirect()->back()
                ->withInput()
                ->with('error', $msg);
        }
    }

    /**
     * handles image upload for user
     *
     * @param Request $request
     * @param User $user
     * @return void
     */
    protected function handleImageUpload(Request $request, User $user)
    {
        if ($request->hasFile('image')) {
            $user->addMedia($request->image)->toMediaCollection('avatar');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);

        if ($user->canDelete()) {
            $user->roles()->detach();
            $user->privileges()->detach();
            $user->delete();

            $msg = [
                'title'   => 'Staff Account Deleted',
                'message' => 'staff account was successfully deleted'
            ];

            request()->session()->flash('success', $msg);

            return response()->json([
                'success'  => true,
                'redirect' => route('admin.staff.index'),
                'message'  => $msg['message']
            ]);
        }

        return response()->json([
            'success' => false,
            'message' => 'Operation failed! Try again'
        ]);
    }

    /**
     * suspends staff account
     *
     * @param User $staff
     * @return \Illuminate\Http\Response
     */
    public function suspend(User $staff)
    {
        if ($staff->isSuspended()) {
            return response()->json([
                'success' => false,
                'message' => 'staff already suspended'
            ], 400);
        }

        $staff->update([
            'suspended_at' => Carbon::now(),
            'suspended_by' => auth()->user()->id,
        ]);

        return response()->json([
            'success' => true,
            'message' => 'staff, '.$staff->full_name.' was successfully suspended'
        ]);
    }

    /**
     * unsuspends staff account
     *
     * @param User $staff
     * @return \Illuminate\Http\Response
     */
    public function unsuspend(User $staff)
    {
        if (!$staff->suspended_at) {
            return response()->json([
                'success' => false,
                'message' => 'staff was never suspended',
            ], 400);
        }

        $staff->update([
            'suspended_at' => null,
            'suspended_by' => null,
        ]);

        return response()->json([
            'success' => true,
            'message' => 'staff, '.$staff->full_name.' was successfully unsuspended',
        ]);
    }

    public function updateBranches(Request $request, User $staff)
    {
        $request->validate([
            'branches' => 'required',
        ]);

        try {
            $staff->branches()->sync($request->branches);

            $msg = [
                'title' => 'Staff Branches Updated',
                'message' => 'staff branches was successfully updated',
            ];

            Util::flash('success', $msg);

            return response()->json([
                'success' => true,
                'message' => $msg['message'],
            ]);

        } catch (Exception $ex) {
            
            Log::error($ex->getMessage());

            return response()->json([
                'success' => false,
                'message' => 'Ops! branch assignment failed! Try again',
            ]);
        }
    }
}

resources/views/admin/staff/assign-branches.blade.php
{{-- update branches --}}
<div class="modal fade" id="assign_branches_modal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form action="{{ route('admin.staff.branches.update', $user->id) }}" method="POST">
                @csrf
                <div class="modal-header">
                    <h4 class="modal-title">Branches</h4>
                    <button class="close" data-dismiss="modal" type="button">
                        <span>&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="branches">Branches</label>
                        <x-form.select
                            name="branches[]"
                            id="branches"
                            multiple
                        >
                            @foreach ($branches as $branch)
                                <option
                                    value="{{ $branch->id }}"
                                    @if (in_array($branch->id, $user->branches->pluck('id')->toArray()))
                                        selected
                                    @endif
                                >
                                    {{ $branch->city .'-'. $branch->name }}
                                </option>
                            @endforeach
                        </x-form.select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-outline-secondary waves-effect" type="button" data-dismiss="modal">
                        Dismiss
                    </button>
                    <button class="btn btn-secondary waves-effect" type="submit">
                        Save
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/admin/staff/card.blade.php
<div class="text-center card-box">
    <div class="pt-2 pb-2">
        <img src="{{ $user->avatarThumbnail() }}" class="rounded-circle img-thumbnail avatar-xl" alt="profile-image">

        <h4 class="mt-3"><a href="extras-profile.html" class="text-dark">{{ $user->full_name }}</a></h4>
        <p class="text-muted">
            <small> <a href="#" class="text-green">{{ $user->email }}</a> </small>
        </p>
        <div class="text-center">
            @if ($user->roles->isNotEmpty())
                <p title="{{ implode(", ", $user->roleNamesArray()) }}">
                    <span class="badge badge-dark">{{ $user->roles->count() }} roles</span>
                </p>
            @else
                <p>No role</p>
            @endif
        </div>

        <a class="btn btn-dark waves-effect mt-2" href="{{ route('admin.staff.show', $user->id) }}">
            See Details
        </a>
    </div>
</div>

resources/views/admin/staff/index.blade.php
@extends('layouts.admin.app')

@section('title', 'All Staff')
@section('page_title', 'All Staff')

@push('breadcrumb')
    <li class="breadcrumb-item active">
        Staff
    </li>
@endpush

@push('css')
    
@endpush

@section('content')
    <div class="row mb-3">
        {{-- search form --}}
        <div class="col-md-4">
            <form class="form-inline">
                <div class="input-group">
                    <x-form.input
                        name="search"
                        value="{{ $search }}"
                        class="bg-transparent"
                        placeholder="Search..."
                    ></x-form.input>
                </div>
                <div class="input-group-append">
                    <button class="btn btn-secondary waves-effect">
                        <span class="fa fa-search"></span>
                    </button>
                </div>
            </form>
        </div>
        <div class="col-md-4"></div>
        {{-- add new --}}
        <div class="col-md-4 text-right">
            <a href="{{ route('admin.staff.create') }}" class="btn btn-secondary waves-effect">
                New Staff
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            @if ($users->isNotEmpty())
                @if ($search)
                    <div class="alert alert-light mb-2">
                        {{ $users->total() }} staff found for <span class="text-warning">{{ $search }}</span>
                    </div>
                @endif
                <div class="row">
                    @foreach ($users as $user)
                        <div class="col-lg-4 col-md-12">
                            @include('admin.staff.card')
                        </div>  
                    @endforeach
                </div>
            @else
                @if ($search)
                    <div class="text-center my-3">
                        <h2 class="text-muted">No staff found for <span class="bg-warning text-white">{{ $search }}</span></h2>

                        <a class="btn btn-secondary waves-effect my-2" href="{{ route('admin.staff.index') }}">Return back</a>
                    </div>
                @else                    
                    <div class="text-center my-3">
                        <h2 class="text-muted">No staff found</h2>
                    </div>
                @endif
            @endif
        </div>
        <div class="col-12">
            {{ $users->links() }}
        </div>
    </div>
@endsection

@push('js')
    
@endpush

resources/views/admin/staff/show.blade.php
@extends('layouts.admin.app')

@section('title', 'Staff - '.$user->full_name)
@section('page_title', $user->full_name)

@push('breadcrumb')
    <li class="breadcrumb-item">
        <a href="{{ route('admin.staff.index') }}">Staff</a>
    </li>
    <li class="breadcrumb-item active">
        {{ Str::limit($user->full_name, 15) }}
    </li>
@endpush

@push('css')
    <link rel="stylesheet" href="{{ asset('css/select2.min.css') }}">
@endpush

@section('content')
    <div class="jumbotron profile-jumbotron jumbotron-bg-1">
        <div class="text-center">
            <div class="">
                <img src="{{ $user->avatarThumbnail() }}" class="img-thumbnail rounded-circle mx-auto avatar-xl" alt="profile-image">
            </div>
            <div class="py-2">
                <h2 class="text-white">{{ $user->full_names }}</h2>
                <p><a class="text-warning" href="mailto:{{ $user->email }}">{{ $user->email }}</a></p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 order-3 order-md-1">
            {{-- profile details --}}
            <div class="card">
                <div class="card-body">
                    <div class="card-widgets">
                        <a data-toggle="collapse" href="#cardPriv" role="button" aria-expanded="false" aria-controls="cardCollpase1"><i class="mdi mdi-minus"></i></a>
                    </div>
                    <h5 class="card-title mb-0"> Profile Information</h5>
                    <div id="cardPriv" class="collapse pt-3 show">
                        <h4 class="font-13 text-muted text-uppercase">Email :</h4>
                        <p class="mb-3">{{ $user->email }}</p>

                        <h4 class="font-13 text-muted text-uppercase">Phone :</h4>
                        <p class="mb-3">{{ $user->phone }}</p>

                        <h4 class="font-13 text-muted text-uppercase">Address :</h4>
                        <p class="mb-3">{{ $user->address ?? '-' }}</p>
                    </div>
                </div>
            </div>
            {{-- branches details --}}
            <div class="card">
                <div class="card-body">
                    <div class="card-widgets">
                        <a data-toggle="collapse" href="#cardBranch" role="button" aria-expanded="false" aria-controls="cardBranch"><i class="mdi mdi-minus"></i></a>
                        <a href="javascript:;" class="assign_branches_btn" role="button"><i class="mdi mdi-tooltip-edit"></i></a>
                    </div>
                    <h5 class="card-title mb-0">Assign Branches</h5>
                    <div id="cardBranch" class="collapse pt-3 show">
                       @if ($user->branches->isNotEmpty())
                           <div class="row">
                               @foreach ($user->branches as $branch)
                                   <div class="col-md-4">
                                       <span class="chip">{{ $branch->city }} - {{ $branch->name }}</span>
                                   </div>
                               @endforeach
                           </div>
                       @else
                           <div class="text-center my-4">
                               <h5 class="text-muted">No branch assigned!</h5>
                           </div>
                       @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-1 order-2"></div>
        <div class="col-md-3 order-1 order-md-2">
            <button class="btn btn-secondary btn-block d-md-none mb-3"><i class="fa fa-nav"></i>Toggle Actions</button>
            <div class="mobile-menu d-none d-md-block">
                <a href="{{ route('admin.staff.edit', $user->id) }}" class="btn btn-warning btn-block waves-effect mb-2">
                    Edit Account
                </a>
                <a href="{{ route('admin.staff.noks', $user->id) }}" class="btn btn-dark btn-block waves-effect mb-2">
                    Next of Kin
                </a>
                @if ($user->isSuspended())                    
                    <button class="btn btn-dark btn-block waves-effect mb-2 unsuspend_user_btn"
                        data-url=""
                        data-name="{{ $user->full_name }}"    
                    >
                        Unsuspend Account
                    </button>
                @else
                    <button class="btn btn-dark btn-block waves-effect mb-2 suspend_user_btn"
                        data-url=""
                        data-name="{{ $user->full_name }}"
                    >
                        Suspend Account
                    </button>
                @endif
                
                <a href="{{ route('admin.staff.roles', $user->id) }}" class="btn btn-dark btn-block waves-effect mb-2">
                    Roles & Privileges
                </a>

                @if ($user->canDelete())                    
                <button class="btn btn-danger btn-block mb-2 waves-effect delete_user_btn"
                    data-name="{{ $user->full_name }}"
                    data-ur="{{ route('admin.staff.destroy', $user->id) }}"
                >
                    Delete Account
                </button>
                @endif
                <button class="btn btn-dark btn-block waves-effect mb-2 assign_branches_btn">
                     Branches
                </button>
            </div>
        </div>
    </div>

    {{-- modals --}}
    @include('admin.staff.assign-branches')
@endsection

@push('js')
    <script src="{{ asset('js/select2.min.js') }}"></script>
    <script src="{{ asset('js/admin/staff.js') }}"></script>

    <script>
        $(document).ready(function() {
            $('#branches').select2({
                placeholder: 'pick branches'
            });
        });
    </script>
@endpush