routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group([
    'middleware' => 'auth',
    'prefix'     => 'admin',
    'as'         => 'admin.',
    'namespace'  => 'Admin',
], function() {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    // staff roles
    Route::resource('staff/roles', 'RoleController');
    // staff privileges
    Route::resource('staff/privileges', 'PrivilegeController');
    // staff
    Route::resource('staff', 'StaffController');
    Route::post('staff/{staff}/suspend', 'StaffController@suspend')->name('staff.suspend');
    Route::post('staff/{staff}/unsuspend', 'StaffController@unsuspend')->name('staff.unsuspend');
    // staff nok
    Route::get('staff/{staff}/noks', 'StaffNokController@index')->name('staff.noks');
    Route::get('staff/{staff}/noks/create', 'StaffNokController@create')->name('staff.noks.create');
    Route::post('staff/{staff}/noks/store', 'StaffNokController@store')->name('staff.noks.store');
    Route::get('staff/{staff}/noks/{nok}' , 'StaffNokController@show')->name('staff.noks.show');
    Route::get('staff/{staff}/noks/{nok}/edit', 'StaffNokController@edit')->name('staff.noks.edit');
    Route::put('staff/{staff}/noks/{nok}/update', 'StaffNokController@update')->name('staff.noks.update');
    Route::delete('staff/{staff}/noks/{nok}/destroy', 'StaffNokController@destroy')->name('staff.noks.destroy');
    // branches
    Route::post('staff/{staff}/branches', 'StaffController@updateBranches')->name('staff.branches.update');
    // staff role and privileges..
    Route::get('staff/{staff}/roles','StaffRoleController@index')->name('staff.roles');
    Route::put('staff/{staff}/roles', 'StaffRoleController@update')->name('staff.roles.update');
    Route::get('staff/{staff}/roles/edit', 'StaffRoleController@edit')->name('staff.roles.edit');
    Route::put('staff/{staff}/privileges', 'StaffRoleController@updatePrivileges')->name('staff.privileges.update');

    // customers
    Route::resource('customers', 'CustomerController');
    Route::get('customers/{customer}/vehicles', 'CustomerVehicleController@index')->name('customers.vehicles');

    // branch
    Route::resource('settings/branches', 'BranchController');
    Route::get('settings/branches/{branch}/staff', 'BranchController@staff')->name('branches.staff');
    Route::get('settings/branches/{branch}/customers', 'BranchController@customers')->name('branches.customers');
    // services
    Route::resource('settings/services', 'ServiceController');

    // product type
    Route::resource('products/product-type', 'ProductTypeController');

    // product
    Route::resource('products', 'ProductController');

    // vehicle fuels
    Route::resource('vehicles/vehicle-fuels', 'VehicleFuelController');
    // vehicle make
    Route::resource('vehicles/vehicle-makes', 'VehicleMakeController');
    // vehicles
    Route::resource('vehicles', 'VehicleController');
    // supplies
    Route::resource('supplies', 'SupplyController');

    Route::post('supplies/{supply}/confirm', 'SupplyController@confirmSupply')->name('supplies.confirm');
    Route::post('supplies/{supply}/items', 'SupplyItemController@store')->name('supplies.add.item');
    Route::get('supplies/{supply}/items/{id}', 'SupplyItemController@show')->name('supplies.show.item');
    Route::put('supplier/{supply}/items/{id}', 'SupplyItemController@update')->name('supplies.update.item');
    Route::delete('supplier/{supply}/items/{id}', 'SupplyItemController@destroy')->name('supplies.destroy.item');
    // suppliers
    Route::resource('suppliers', 'SupplierController');
    // job order
    Route::resource('job-orders', 'JobOrderController');
    Route::post('job-orders/{order}/manager', 'JobOrderController@assignManager')->name('job-orders.manager');

    Route::get('job-orders/{order}/inspection', 'JobOrderInspectionController@index')->name('job-orders.inspection');
    Route::put('job-orders/{order}/inspection', 'JobOrderInspectionController@update')->name('job-orders.inspection.update');
    Route::post('job-orders/{order}/inspection/results', 'JobOrderInspectionController@addItem')->name('job-orders.inspection.add-item');
    Route::put('job-orders/{order}/inspection/results/{result}', 'JobOrderInspectionController@updateItem')->name('job-orders.inspection.update-item');
    Route::delete('job-orders/{order}/inspection/results/{result}', 'JobOrderInspectionController@removeItem')->name('job-orders.inspection.remove-item');

    Route::get('job-orders/{order}/faults', 'JobOrderFaultController@index')->name('job-orders.faults');
    Route::post('job-orders/{order}/faults', 'JobOrderFaultController@store')->name('job-orders.faults.store');
    Route::get('job-orders/{order}/faults/create', 'JobOrderFaultController@create')->name('job-orders.faults.create');
    Route::put('job-orders/{order}/faults/{id}', 'JobOrderFaultController@update')->name('job-orders.faults.update');
    Route::delete('job-orders/{order}/faults/{id}', 'JobOrderFaultController@destroy')->name('job-orders.faults.destroy');

    Route::get('job-orders/{order}/services', 'JobOrderServiceController@index')->name('job-orders.services');
    Route::post('job-orders/{order}/services', 'JobOrderServiceController@store')->name('job-orders.services.store');
    Route::get('job-orders/{order}/services/{service}', 'JobOrderServiceController@show')->name('job-orders.services.show');
    Route::put('job-orders/{order}/services/{service}', 'JobOrderServiceController@update')->name('job-orders.services.update');
    Route::delete('job-orders/{order}/services/{service}', 'JobOrderServiceController@destroy')->name('job-orders.services.destroy');
    Route::get('job-orders/{order}/services/{service}/edit', 'JobOrderServiceController@edit')->name('job-orders.services.edit');

});

app/Http/Controllers/Admin/StaffController.php
<?php

namespace App\Http\Controllers\Admin;

use Exception;
use Carbon\Carbon;
use App\Models\Role;
use App\Models\User;
use App\Helpers\Util;
use App\Models\Branch;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use App\Http\Controllers\Controller;

class StaffController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $per_page = 9;
        $search = strtolower($request->search) ?? null;

        if ($search) {
            $users = User::where('first_name', 'LIKE', $search.'%')
                ->orWhere('last_name', 'LIKE', $search,'%')
                ->orWhere('middle_name', 'LIKE', $search.'%')
                ->orWhere('email', 'LIKE', $search.'%')
                ->orWhere('phone', 'LIKE', $search.'%')
                ->paginate($per_page);
        } else {
            $users = User::orderByDesc('id')->paginate($per_page);
        }
        
        return view('admin.staff.index')
            ->with('users', $users)
            ->with('search', $search);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::has('privileges')->get();
        $genders = User::genders;
        $branches = Branch::all();

        return view('admin.staff.create')
            ->with('roles', $roles)
            ->with('genders', $genders)
            ->with('branches', $branches);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'first_name'    => 'required|string|max:191',
            'middle_name'   => 'nullable|string|max:191',
            'last_name'     => 'required|string|max:191',
            'email'         => 'required|string|max:191|email|unique:users,email',
            'phone'         => 'required|string|digits_between:7,15',
            'gender'        => 'required|string',
            'dob'           => 'nullable|date',
            'address'       => 'nullable|string',
            'roles'         => 'required',
            'image'         => 'nullable|image|mimes:jpg,png,gif,jpeg|max:500',
        ], [], [
            'dob' => 'date of birth',
        ]);

        $request->request->add(['branch_id' => $this->currentBranch()->id ]);
        
        try {
            //code...
            $user = User::create($request->all());
            
            // assign role/privileges
            $user->assignRoles($request->roles);
            $this->handleImageUpload($request, $user);

            // assign branch
            $user->branches()->attach($this->currentBranch()->id);

            $msg = [
                'title'    => 'Staff Account Created',
                'message' => 'staff account for , '.$user->full_name.'  was successfully created',
            ];

            return redirect()->route('admin.staff.show', $user->id)
                ->with('success', $msg);

        } catch (Exception $ex) {
            //log error
            Log::error($ex->getMessage());

            $msg = [
                'title'   => 'Account Creation Failed',
                'message' => 'account was not created! Try again!'
            ];

            return redirect()->back()
                ->with('error', $msg)
                ->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);
        $branches  = Branch::all();

        return view('admin.staff.show')
            ->with('user', $user)
            ->with('branches', $branches);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::with(['roles'])->findOrFail($id);
        $genders = User::genders;

        return view('admin.staff.edit')
            ->with('user', $user)
            ->with('genders', $genders);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'first_name'  => 'required|string|max:191',
            'middle_name' => 'nullable|string|max:191',
            'last_name'   => 'required|string|max:191',
            'email'       => 'required|string|max:191|email|unique:users,email,'.$request->email.',email',
            'phone'       => 'required|string|digits_between:7,15',
            'gender'      => 'required|string',
            'dob'         => 'nullable|date',
            'address'     => 'nullable|string',
            'image'       => 'nullable|image|mimes:jpg,jpeg,png,gif|max:500',
        ], [], [
            'dob' => 'date of birth',
        ]);

        $user = User::findOrFail($id);

        try {
            
        $user->update($request->all());
            $this->handleImageUpload($request, $user);

            $msg = [
                'title'   => 'Staff Account Updated',
                'message' => 'staff account was successfully updated'
            ];

            return redirect()->route('admin.staff.show', $id)
                ->with('success', $msg);

        } catch (Exception $ex) {
            //log error
            Log::error($ex->getMessage());

            $msg = [
                'title'   => 'Update Failed',
                'message' => 'staff update failed! Try again'
            ];

            return redirect()->back()
                ->withInput()
                ->with('error', $msg);
        }
    }

    /**
     * handles image upload for user
     *
     * @param Request $request
     * @param User $user
     * @return void
     */
    protected function handleImageUpload(Request $request, User $user)
    {
        if ($request->hasFile('image')) {
            $user->addMedia($request->image)->toMediaCollection('avatar');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);

        if ($user->canDelete()) {
            $user->roles()->detach();
            $user->privileges()->detach();
            $user->delete();

            $msg = [
                'title'   => 'Staff Account Deleted',
                'message' => 'staff account was successfully deleted'
            ];

            request()->session()->flash('success', $msg);

            return response()->json([
                'success'  => true,
                'redirect' => route('admin.staff.index'),
                'message'  => $msg['message']
            ]);
        }

        return response()->json([
            'success' => false,
            'message' => 'Operation failed! Try again'
        ]);
    }

    /**
     * suspends staff account
     *
     * @param User $staff
     * @return \Illuminate\Http\Response
     */
    public function suspend(User $staff)
    {
        if ($staff->isSuspended()) {
            return response()->json([
                'success' => false,
                'message' => 'staff already suspended'
            ], 400);
        }

        $staff->update([
            'suspended_at' => Carbon::now(),
            'suspended_by' => auth()->user()->id,
        ]);

        return response()->json([
            'success' => true,
            'message' => 'staff, '.$staff->full_name.' was successfully suspended'
        ]);
    }

    /**
     * unsuspends staff account
     *
     * @param User $staff
     * @return \Illuminate\Http\Response
     */
    public function unsuspend(User $staff)
    {
        if (!$staff->suspended_at) {
            return response()->json([
                'success' => false,
                'message' => 'staff was never suspended',
            ], 400);
        }

        $staff->update([
            'suspended_at' => null,
            'suspended_by' => null,
        ]);

        return response()->json([
            'success' => true,
            'message' => 'staff, '.$staff->full_name.' was successfully unsuspended',
        ]);
    }

    public function updateBranches(Request $request, User $staff)
    {
        $request->validate([
            'branches' => 'required',
        ]);

        try {
            $staff->branches()->sync($request->branches);

            $msg = [
                'title' => 'Staff Branches Updated',
                'message' => 'staff branches was successfully updated',
            ];

            Util::flash('success', $msg);

            return response()->json([
                'success' => true,
                'message' => $msg['message'],
            ]);

        } catch (Exception $ex) {
            
            Log::error($ex->getMessage());

            return response()->json([
                'success' => false,
                'message' => 'Ops! branch assignment failed! Try again',
            ]);
        }
    }
}

resources/views/admin/staff/noks/edit.blade.php
@extends('layouts.admin.app')

@section('title', $user->full_name. ' - NOKs Update')
@section('page_title', $user->full_name. ' - Next Of Kins Update')

@push('breadcrumb')
    <li class="breadcrumb-item">
        <a href="{{ route('admin.staff.index') }}">Staff</a>
    </li>
    <li class="breadcrumb-item">
        <a href="{{ route('admin.staff.show', $user->id) }}">{{ Str::limit($user->full_name, 15) }}</a>
    </li>
    <li class="breadcrumb-item">
        <a href="{{ route('admin.staff.noks', $user->id) }}">NOKs</a>
    </li>
    <li class="breadcrumb-item">
        <a href="{{ route('admin.staff.noks.show', [$user->id, $nok->id]) }}">{{ $nok->reference }}</a>
    </li>
    <li class="breadcrumb-item">
        Edit
    </li>
@endpush

@push('css')
    <link rel="stylesheet" href="{{ asset('css/drop_uploader.css') }}">
@endpush

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <form action="{{ route('admin.staff.noks.update',[ $user->id, $nok->id]) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('put')
                    <div class="card-body">
                         <h4 class="header-title">Edit Next of Kin</h4>
                        <p class="font-13 sub-header"></p>

                        <div class="row">
                            <div class="offset-md-3 col-md-6">
                                @if ($errors->any())
                                    <div class="alert alert-danger alert-dismissable">
                                        {{ $errors->first() }}
                                        <button class="close" type="submit"><span>&times;</span></button>
                                    </div>
                                @endif
                                <div class="form-group">
                                    <label for="first_name">First Name</label>
                                    <x-form.input
                                        name="first_name"
                                        id="first_name"
                                        required
                                        value="{{ old('first_name') ?? $nok->first_name }}"
                                    ></x-form.input>
                                </div>
                                <div class="form-group">
                                    <label for="last_name">Last Name</label>
                                    <x-form.input
                                        name="last_name"
                                        id="last_name"
                                        value="{{ old('last_name') ?? $nok->last_name }}"
                                    ></x-form.input>
                                </div>

                                <div class="form-group">
                                    <label for="email">Email</label>
                                    <x-form.input
                                        name="email"
                                        type="email"
                                        id="email"
                                        value="{{ old('email') ?? $nok->email }}"
                                    ></x-form.input>
                                </div>

                                <div class="form-group">
                                    <label for="phone">Phone</label>
                                    <x-form.input
                                        name="phone"
                                        id="phone"
                                        value="{{ old('phone') ?? $nok->phone }}"
                                        required
                                    ></x-form.input>
                                </div>

                                <div class="form-group">
                                    <label for="relationship">Relationship</label>
                                    <x-form.input
                                        name="relationship"
                                        id="relationship"
                                        value="{{ old('relationship') ?? $nok->relationship}}"
                                        required
                                    ></x-form.input>
                                </div>

                                <div class="form-group">
                                    <label for="occupation">occupation</label>
                                    <x-form.input
                                        name="occupation"
                                        id="occupation"
                                        value="{{ old('occupation') ?? $nok->occupation }}"
                                        required
                                    ></x-form.input>
                                </div>
                                
                                <div class="form-group">
                                    <label for="address">Address</label>
                                    <x-form.textarea
                                        name="address"
                                        id="address"
                                    >{{ old('address') ?? $nok->address }}</x-form.textarea>
                                </div>

                                <div class="form-group">
                                    <label for="image">Image</label>
                                    <x-form.input
                                        name="image"
                                        id="image"
                                        type="file"
                                    ></x-form.input>
                                </div>

                                <div class="form-group text-center my-4">
                                    <button type="submit" class="btn btn-secondary waves-effect px-5">
                                        Save
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <script src="{{ asset('js/drop_uploader.js') }}"></script>
    <script src="{{ asset('js/admin/staff.js') }}"></script>

@endpush

resources/views/admin/staff/noks/index.blade.php
@extends('layouts.admin.app')

@section('title', $user->full_name. ' - NOKs')
@section('page_title', $user->full_name. ' - Next Of Kins')

@push('breadcrumb')
    <li class="breadcrumb-item">
        <a href="{{ route('admin.staff.index') }}">Staff</a>
    </li>
    <li class="breadcrumb-item ">
        <a href="{{ route('admin.staff.show', $user->id) }}">{{ Str::limit($user->full_name, 15) }}</a>
    </li>
    <li class="breadcrumb-item active">
        NOKs
    </li>
@endpush

@push('css')
    
@endpush

@section('content')
    @if ($user->noks->isNotEmpty())
        <div class="row">
            <div class="col-12 text-right mb-2">
                <a href="{{ route('admin.staff.noks.create', $user->id) }}" class="btn btn-secondary waves-effect">
                    New Next of Kin
                </a>
            </div>
            @foreach ($user->noks as $nok)
                <div class="col-12 mb-2">
                    <div class="card-box">
                        <div class="row">
                            <div class="col-md-3 text-center">
                                <img src="{{ $nok->avatarThumbnail() }}" class="img-thumbnail avatar-xxl" />
                            </div>
                            <div class="col-md-9">
                                <h4>{{ $nok->full_name }}</h4>
                                <p>
                                    <i class="fa fa-phone mr-1"></i>
                                    Telephone:
                                    <span class="text-muted ml-2"><a href="tel:{{ $nok->phone }}">{{ $nok->phone }}</a></span>
                                </p>
                                <p>
                                    <i class="fa fa-envelope mr-1"></i>
                                    Email:
                                    @if ($nok->email)
                                        <span class="text-muted ml-2"><a href="mailto:{{ $nok->email }}">{{ $nok->email }}</a></span>
                                    @else
                                        '-'
                                    @endif
                                </p>

                                <p>
                                    <i class="fa fa-user-friends mr-1"></i>
                                    Relationship:
                                    <span class="text-muted ml-2">{{ $nok->relationship }}</span>
                                </p>
                            </div>
                        </div>
                        <div class="text-right">
                            <a class="btn btn-secondary waves-effect" href="{{ route('admin.staff.noks.show', [$user->id, $nok->id]) }}">
                                View
                            </a>
                            <a class="btn btn-warning waves-effect" href="{{ route('admin.staff.noks.edit', [$user->id, $nok->id]) }}"
                                title="Edit"    
                            >
                                <span class="fa fa-edit"></span>
                            </a>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    @else
        <div class="text-center my-5">
            <h2 class="text-muted">No Next of Kin found!</h2>
            <a href="{{ route('admin.staff.noks.create', $user->id) }}" class="btn btn-secondary waves-effect my-2">
                Add New Next of Kin
            </a>
        </div>
    @endif
@endsection

@push('js')
    
@endpush

resources/views/admin/staff/noks/show.blade.php
@extends('layouts.admin.app')

@section('title', $user->full_name. ' - NOKs')
@section('page_title', $user->full_name. ' - Next Of Kins Details')

@push('breadcrumb')
    <li class="breadcrumb-item">
        <a href="{{ route('admin.staff.index') }}">Staff</a>
    </li>
    <li class="breadcrumb-item ">
        <a href="{{ route('admin.staff.show', $user->id) }}">{{ Str::limit($user->full_name, 15) }}</a>
    </li>
    <li class="breadcrumb-item active">
        <a href="{{ route('admin.staff.noks', $user->id) }}">NOKs</a>
    </li>
    <li class="breadcrumb-item active">
        {{ $nok->reference }}
    </li>
@endpush

@push('css')
    
@endpush

@section('content')
   <div class="row">
       <div class="col-12">
            <div class="mb-2 text-right">
                <a class="btn btn-warning waves-effect" href="{{ route('admin.staff.noks.edit', [$user->id, $nok->id]) }}">
                    Edit
                </a>
                <button class="btn btn-danger waves-effect delete_nok_btn"
                    data-name="{{ $nok->full_name }}"
                    data-url="{{ route('admin.staff.noks.destroy', [$user->id, $nok->id]) }}"
                >
                    Delete
                </button>
            </div>
            <div class="card">
                <div class="card-body">
                    <div class="card-widgets">
                    </div>
                    <h5 class="card-title mb-0"> Profile Information</h5>
                    <div id="cardPriv" class="collapse pt-3 show">
                        <div class="row">
                            <div class="col-md-3 text-center">
                                <img src="{{ $nok->avatarThumbnail() }}"  class="img-thumbnail avatar-xxl d-block mx-auto" />
                                <h5 class="my-2">{{ $nok->full_name }}</h5>
                            </div>
                            <div class="col-md-9">
                                <h4 class="font-13 text-muted text-uppercase">Relationship :</h4>
                                <p class="mb-3">{{ $nok->relationship ?? '-' }}</p>

                                <h4 class="font-13 text-muted text-uppercase">Occupation :</h4>
                                <p class="mb-3">{{ $nok->occupation ?? '-' }}</p>

                                <h4 class="font-13 text-muted text-uppercase">Email :</h4>
                                <p class="mb-3">{{ $nok->email ?? '-' }}</p>
        
                                <h4 class="font-13 text-muted text-uppercase">Phone :</h4>
                                <p class="mb-3">{{ $nok->phone ?? '-' }}</p>
        
                                <h4 class="font-13 text-muted text-uppercase">Address :</h4>
                                <p class="mb-3">{{ $nok->address ?? '-' }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
       </div>
   </div>
@endsection

@push('js')
    <script src="{{ asset('js/admin/staff.js') }}"></script>
@endpush